version: '3.9'

services:
  nextjs:
    container_name: resto-nextjs
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    entrypoint: /bin/sh -c "npm install && npm run dev"

  nextjs-prod:
    container_name: resto-nextjs-prod
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    entrypoint: /bin/sh -c "npm install && npm run build && npm run start"